apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "user-api.fullname" . }}
  labels:
    {{- include "user-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.size }}
  {{- if .Values.postgres.pvc.storageClass }}
  storageClassName: {{ .Values.postgres.pvc.storageClass }}
  {{- end }}
